# Generated by Django 3.2.9 on 2021-11-29 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_students'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
